on: [push]
  
jobs:
  build:
    env:
      IMAGE_NAME: quay.io/eclipse/che-sidecar-camelk
    runs-on: ubuntu-latest
    steps:
    
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: this-repo

    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        repository: eclipse/che-plugin-registry
        path: this-repo/plugin-registry
    
    - name: ls
      id: list
      uses: che-dockerfiles/plugin-sidecar-update-action@v4
      with:
        plugin-registry: this-repo/plugin-registry
    
    - name: Get output
      run: |
        cat this-repo/plugin-registry/vscode-extensions.json

    - name: Set git user
      run: |
        cd this-repo/plugin-registry
        git config user.email che-bot@eclipse.org
        git config user.name "CHE Bot"

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Test PR"
        author: CHE Bot <che-bot@eclipse.org>
        signoff: CHE Bot <che-bot@eclipse.org>
        branch: test-sidecar-update-action-pr
        path: this-repo/plugin-registry
        base: ${{ github.head_ref }}