on: [push]
  
jobs:
  build:
    env:
      IMAGE_NAME: quay.io/eclipse/che-sidecar-camelk
    runs-on: ubuntu-latest
    steps:
    
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: this-repo

    - name: Clone source code
      uses: actions/checkout@v2
      with:
        repository: ericwill/che-plugin-registry
        path: this-repo/plugin-registry
    
    - name: ls
      id: list
      uses: che-dockerfiles/plugin-sidecar-update-action@v2
      with:
        plugin-registry: this-repo/plugin-registry
    
    - name: Get output
      run: |
        cat this-repo/plugin-registry/vscode-extensions.json